Repository GestionCIE/CIE-back, pull requests merged in 2020-07, with the labels that each got.

#22 Developer
  infrastructure/structureDB.js
  models/ProjectModel.js
  models/eventModel.js
  models/userModel.js
  routes/event.js
  routes/project.js
  routes/tracing.js
  routes/users.js
Labels: enhancement

#26 grafica
  routes/project.js
Labels: enhancement

#29 se trabajo en las notificaciones con socketio, se añadio nueva tabla …
  infrastructure/SocketServer.js
  infrastructure/structureDB.js
  models/userModel.js
Labels: enhancement

#31 Developer
  infrastructure/ManagerEmail.js
  infrastructure/SocketServer.js
  infrastructure/structureDB.js
  models/ProjectModel.js
  models/eventModel.js
  models/notificationModel.js
  models/serviceModel.js
  models/tracingModel.js
  package-lock.json
  package.json
  routes/project.js
  routes/tracing.js
Labels: bug, enhancement

#32 Developer
  infrastructure/structureDB.js
  models/configModel.js
  routes/config.js
Labels: enhancement

#34 se agregro una estructura try catch en una de las rutas de tracing.js…
  models/eventModel.js
  routes/tracing.js
Labels: bug

#37 Developer
  infrastructure/structureDB.js
  models/tracingModel.js
  routes/event.js
  routes/tracing.js
Labels: bug, refactoring

#40 Developer
  .gitignore
  ecosystem.config.js
  infrastructure/ManagerEmail.js
  infrastructure/ManagerFilesServer.js
  infrastructure/Notification.js
  infrastructure/SocketServer.js
  package-lock.json
  package.json
  routes/users.js
Labels: bug, enhancement, refactoring
